name: Deploy to Laptop Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Windows Server
      uses: appleboy/ssh-action@v1.1.0
      with:
        host: ${{ vars.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          ${{ vars.DEPLOY_SCRIPT }} ${{ vars.APP_DIR }} ${{ vars.DOCKER_SERVICE }}
