name: Deploy to Laptop Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Windows Server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd C:\Danil\MyApps\Apps\Defender.IdentityService\
          git pull origin main
          cd ../..
          docker-compose -f dev-core-docker-compose.yml -p dev up -d --build dev-identity-service
